### ISSUE TITLE
Error: Worker error: "error.message.trim is not a function"

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#582]
The following issue blocked us to deploy console-vue in stage
https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-vue/684/console

Root Cause:
- Child process does not contain `message` as a property in error and as a result can not access it and crashes

Note:
- realtime/create endpoint will not be called to log failed status in console

ETA to debug and fix ~ 1 hour

**Comment by vcalmic** [comment]
Fixed:
https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-vue/687/console

**Comment by avozicov** [comment]
Deploy succeed https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-api/2073/console, but I still facing the error with `trim is not a function` when getting an error from terraform so we need to investigate and fix it:
Please refer to the following ticket for more details https://github.com/TerraHubCorp/terrahub/issues/584

**Comment by avozicov** [comment]
**Fixed**

- I have executed terrahub without providing required variables and as a result received the expected error message:

<img width="1131" alt="screen shot 2019-02-15 at 6 48 57 pm" src="https://user-images.githubusercontent.com/12330493/52871301-6f8b7300-3152-11e9-8dff-06922f652eab.png">

**Comment by eistrati** [comment]
Checked.
